local PRT = PurplexityRaidTools

PRT.BossTimelineData = {
    schemaVersion = 1,
    encounters = {
        [3379] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1260837, time = 8, observations = 30 },
                                { spellID = 1257717, time = 18, observations = 30 },
                                { spellID = 1282937, time = 27, observations = 30 },
                                { spellID = 1313393, time = 35, observations = 30 },
                                { spellID = 1260837, time = 41, observations = 30 },
                                { spellID = 1282937, time = 49, observations = 30 },
                                { spellID = 1282937, time = 71, observations = 30 },
                                { spellID = 1313393, time = 79, observations = 30 },
                                { spellID = 1260837, time = 85, observations = 30 },
                                { spellID = 1282937, time = 93, observations = 30 },
                                { spellID = 1257717, time = 128, observations = 30 },
                                { spellID = 1282937, time = 137, observations = 30 },
                                { spellID = 1313393, time = 145, observations = 30 },
                                { spellID = 1260837, time = 151, observations = 30 },
                                { spellID = 1282937, time = 159, observations = 30 },
                                { spellID = 1282937, time = 181, observations = 30 },
                                { spellID = 1313393, time = 189, observations = 30 },
                                { spellID = 1260837, time = 195, observations = 30 },
                                { spellID = 1282937, time = 203, observations = 30 },
                                { spellID = 1257717, time = 238, observations = 27 },
                                { spellID = 1282937, time = 247, observations = 24 },
                                { spellID = 1313393, time = 255, observations = 21 },
                                { spellID = 1260837, time = 261, observations = 20 },
                                { spellID = 1282937, time = 269, observations = 20 },
                                { spellID = 1282937, time = 291, observations = 16 },
                                { spellID = 1313393, time = 299, observations = 14 },
                                { spellID = 1260837, time = 305, observations = 11 },
                                { spellID = 1282937, time = 313, observations = 7 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1260837, time = 8, observations = 30 },
                                { spellID = 1257717, time = 18, observations = 30 },
                                { spellID = 1282937, time = 27, observations = 30 },
                                { spellID = 1313393, time = 35, observations = 30 },
                                { spellID = 1260837, time = 41, observations = 30 },
                                { spellID = 1282937, time = 49, observations = 30 },
                                { spellID = 1282937, time = 71, observations = 30 },
                                { spellID = 1313393, time = 79, observations = 30 },
                                { spellID = 1260837, time = 85, observations = 30 },
                                { spellID = 1282937, time = 93, observations = 30 },
                                { spellID = 1257717, time = 128, observations = 30 },
                                { spellID = 1282937, time = 137, observations = 30 },
                                { spellID = 1313393, time = 145, observations = 30 },
                                { spellID = 1260837, time = 151, observations = 30 },
                                { spellID = 1282937, time = 159, observations = 30 },
                                { spellID = 1282937, time = 181, observations = 30 },
                                { spellID = 1313393, time = 189, observations = 30 },
                                { spellID = 1260837, time = 195, observations = 30 },
                                { spellID = 1282937, time = 203, observations = 30 },
                                { spellID = 1257717, time = 238, observations = 30 },
                                { spellID = 1282937, time = 247, observations = 30 },
                                { spellID = 1313393, time = 255, observations = 30 },
                                { spellID = 1260837, time = 261, observations = 30 },
                                { spellID = 1282937, time = 269, observations = 30 },
                                { spellID = 1282937, time = 291, observations = 30 },
                                { spellID = 1313393, time = 299, observations = 30 },
                                { spellID = 1260837, time = 305, observations = 30 },
                                { spellID = 1282937, time = 313, observations = 30 },
                                { spellID = 1257717, time = 348, observations = 29 },
                                { spellID = 1282937, time = 357, observations = 30 },
                                { spellID = 1313393, time = 365, observations = 30 },
                                { spellID = 1260837, time = 371, observations = 30 },
                                { spellID = 1282937, time = 379, observations = 30 },
                                { spellID = 1282937, time = 401, observations = 21 },
                                { spellID = 1313393, time = 409, observations = 18 },
                                { spellID = 1260837, time = 415, observations = 14 },
                                { spellID = 1282937, time = 423, observations = 12 },
                            },
                        },
                    },
                },
                [17] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1260837, time = 8, observations = 25 },
                                { spellID = 1257717, time = 18, observations = 25 },
                                { spellID = 1282937, time = 27, observations = 25 },
                                { spellID = 1313393, time = 35, observations = 25 },
                                { spellID = 1260837, time = 41, observations = 25 },
                                { spellID = 1282937, time = 49, observations = 25 },
                                { spellID = 1282937, time = 71, observations = 24 },
                                { spellID = 1313393, time = 79, observations = 22 },
                                { spellID = 1260837, time = 85, observations = 21 },
                                { spellID = 1282937, time = 93, observations = 20 },
                                { spellID = 1257717, time = 128, observations = 19 },
                                { spellID = 1282937, time = 137, observations = 16 },
                                { spellID = 1313393, time = 145, observations = 14 },
                                { spellID = 1260837, time = 151, observations = 12 },
                                { spellID = 1282937, time = 159, observations = 11 },
                                { spellID = 1282937, time = 181, observations = 6 },
                                { spellID = 1313393, time = 189, observations = 6 },
                                { spellID = 1260837, time = 195, observations = 5 },
                                { spellID = 1282937, time = 203, observations = 5 },
                                { spellID = 1257717, time = 238, observations = 3 },
                                { spellID = 1282937, time = 247, observations = 3 },
                            },
                        },
                    },
                },
            },
        },
        [3420] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 36, observations = 9 },
                                { spellID = 1285425, time = 50, observations = 9 },
                                { spellID = 1305959, time = 95, observations = 9 },
                                { spellID = 1285425, time = 108, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 32, observations = 19 },
                                { spellID = 1285425, time = 44, observations = 19 },
                                { spellID = 1305959, time = 84, observations = 19 },
                                { spellID = 1285425, time = 96, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 34, observations = 19 },
                                { spellID = 1285425, time = 46, observations = 19 },
                                { spellID = 1305959, time = 86, observations = 19 },
                                { spellID = 1285425, time = 98, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 34, observations = 19 },
                                { spellID = 1285425, time = 46, observations = 19 },
                                { spellID = 1305959, time = 86, observations = 19 },
                                { spellID = 1285425, time = 98, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                    },
                },
            },
        },
        [3421] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1289192, time = 10, observations = 30 },
                                { spellID = 1288538, time = 28, observations = 30 },
                                { spellID = 1288538, time = 31, observations = 30 },
                                { spellID = 1288538, time = 35, observations = 30 },
                                { spellID = 1291404, time = 41, observations = 30 },
                                { spellID = 1290809, time = 50, observations = 30 },
                                { spellID = 1290956, time = 59, observations = 30 },
                                { spellID = 1290516, time = 71, observations = 30 },
                                { spellID = 1289192, time = 86, observations = 30 },
                                { spellID = 1288538, time = 104, observations = 30 },
                                { spellID = 1288538, time = 107, observations = 30 },
                                { spellID = 1288538, time = 111, observations = 30 },
                                { spellID = 1291404, time = 117, observations = 30 },
                                { spellID = 1290809, time = 126, observations = 30 },
                                { spellID = 1290956, time = 135, observations = 30 },
                                { spellID = 1290516, time = 148, observations = 30 },
                                { spellID = 1294293, time = 169, observations = 30 },
                                { spellID = 1306872, time = 169, observations = 30 },
                                { spellID = 1289192, time = 198, observations = 30 },
                                { spellID = 1288538, time = 215, observations = 30 },
                                { spellID = 1288538, time = 219, observations = 30 },
                                { spellID = 1288538, time = 222, observations = 30 },
                                { spellID = 1291404, time = 229, observations = 30 },
                                { spellID = 1290809, time = 238, observations = 30 },
                                { spellID = 1290956, time = 246, observations = 30 },
                                { spellID = 1290516, time = 259, observations = 30 },
                                { spellID = 1289192, time = 274, observations = 30 },
                                { spellID = 1288538, time = 291, observations = 30 },
                                { spellID = 1288538, time = 295, observations = 30 },
                                { spellID = 1288538, time = 298, observations = 30 },
                                { spellID = 1291404, time = 305, observations = 30 },
                                { spellID = 1290809, time = 314, observations = 30 },
                                { spellID = 1290956, time = 323, observations = 30 },
                                { spellID = 1290516, time = 335, observations = 30 },
                                { spellID = 1294293, time = 356, observations = 29 },
                                { spellID = 1306872, time = 356, observations = 29 },
                                { spellID = 1289192, time = 385, observations = 27 },
                                { spellID = 1288538, time = 403, observations = 23 },
                                { spellID = 1288538, time = 406, observations = 22 },
                                { spellID = 1288538, time = 410, observations = 21 },
                                { spellID = 1291404, time = 416, observations = 21 },
                                { spellID = 1290809, time = 425, observations = 19 },
                                { spellID = 1290956, time = 434, observations = 19 },
                                { spellID = 1290516, time = 446, observations = 18 },
                                { spellID = 1289192, time = 461, observations = 13 },
                                { spellID = 1288538, time = 479, observations = 9 },
                                { spellID = 1288538, time = 482, observations = 8 },
                                { spellID = 1288538, time = 486, observations = 7 },
                                { spellID = 1291404, time = 493, observations = 8 },
                                { spellID = 1290809, time = 501, observations = 6 },
                                { spellID = 1290956, time = 510, observations = 6 },
                                { spellID = 1290516, time = 523, observations = 4 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1289192, time = 9, observations = 30 },
                                { spellID = 1288538, time = 25, observations = 30 },
                                { spellID = 1288538, time = 28, observations = 30 },
                                { spellID = 1288538, time = 31, observations = 30 },
                                { spellID = 1291404, time = 37, observations = 30 },
                                { spellID = 1290809, time = 44, observations = 30 },
                                { spellID = 1290956, time = 52, observations = 30 },
                                { spellID = 1290516, time = 63, observations = 30 },
                                { spellID = 1289192, time = 77, observations = 30 },
                                { spellID = 1288538, time = 93, observations = 30 },
                                { spellID = 1288538, time = 96, observations = 30 },
                                { spellID = 1288538, time = 99, observations = 30 },
                                { spellID = 1291404, time = 104, observations = 30 },
                                { spellID = 1290809, time = 112, observations = 30 },
                                { spellID = 1290956, time = 120, observations = 30 },
                                { spellID = 1290516, time = 131, observations = 30 },
                                { spellID = 1294293, time = 150, observations = 30 },
                                { spellID = 1306872, time = 150, observations = 30 },
                                { spellID = 1289192, time = 178, observations = 30 },
                                { spellID = 1288538, time = 194, observations = 30 },
                                { spellID = 1288538, time = 197, observations = 30 },
                                { spellID = 1288538, time = 200, observations = 30 },
                                { spellID = 1291404, time = 206, observations = 30 },
                                { spellID = 1290809, time = 214, observations = 30 },
                                { spellID = 1290956, time = 222, observations = 30 },
                                { spellID = 1290516, time = 233, observations = 30 },
                                { spellID = 1289192, time = 246, observations = 30 },
                                { spellID = 1288538, time = 262, observations = 30 },
                                { spellID = 1288538, time = 265, observations = 30 },
                                { spellID = 1288538, time = 268, observations = 30 },
                                { spellID = 1291404, time = 274, observations = 30 },
                                { spellID = 1290809, time = 282, observations = 30 },
                                { spellID = 1290956, time = 289, observations = 30 },
                                { spellID = 1290516, time = 301, observations = 30 },
                                { spellID = 1294293, time = 320, observations = 30 },
                                { spellID = 1306872, time = 320, observations = 30 },
                                { spellID = 1289192, time = 348, observations = 30 },
                                { spellID = 1288538, time = 364, observations = 30 },
                                { spellID = 1288538, time = 367, observations = 30 },
                                { spellID = 1288538, time = 370, observations = 30 },
                                { spellID = 1291404, time = 376, observations = 30 },
                                { spellID = 1290809, time = 383, observations = 30 },
                                { spellID = 1290956, time = 391, observations = 30 },
                                { spellID = 1290516, time = 402, observations = 30 },
                                { spellID = 1289192, time = 416, observations = 29 },
                                { spellID = 1288538, time = 432, observations = 30 },
                                { spellID = 1288538, time = 435, observations = 30 },
                                { spellID = 1288538, time = 438, observations = 30 },
                                { spellID = 1291404, time = 443, observations = 30 },
                                { spellID = 1290809, time = 451, observations = 24 },
                                { spellID = 1290956, time = 459, observations = 21 },
                                { spellID = 1290516, time = 470, observations = 19 },
                            },
                        },
                    },
                },
                [17] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1289192, time = 10, observations = 30 },
                                { spellID = 1288538, time = 27, observations = 30 },
                                { spellID = 1288538, time = 31, observations = 30 },
                                { spellID = 1288538, time = 34, observations = 30 },
                                { spellID = 1291404, time = 41, observations = 30 },
                                { spellID = 1290809, time = 50, observations = 30 },
                                { spellID = 1290956, time = 59, observations = 30 },
                                { spellID = 1290516, time = 71, observations = 30 },
                                { spellID = 1289192, time = 86, observations = 30 },
                                { spellID = 1288538, time = 104, observations = 30 },
                                { spellID = 1288538, time = 107, observations = 30 },
                                { spellID = 1288538, time = 111, observations = 30 },
                                { spellID = 1291404, time = 117, observations = 30 },
                                { spellID = 1290809, time = 126, observations = 30 },
                                { spellID = 1290956, time = 135, observations = 30 },
                                { spellID = 1290516, time = 147, observations = 30 },
                                { spellID = 1294293, time = 169, observations = 30 },
                                { spellID = 1306872, time = 169, observations = 30 },
                                { spellID = 1289192, time = 198, observations = 30 },
                                { spellID = 1288538, time = 215, observations = 30 },
                                { spellID = 1288538, time = 219, observations = 30 },
                                { spellID = 1288538, time = 222, observations = 30 },
                                { spellID = 1291404, time = 229, observations = 30 },
                                { spellID = 1290809, time = 238, observations = 27 },
                                { spellID = 1290956, time = 246, observations = 25 },
                                { spellID = 1290516, time = 259, observations = 20 },
                                { spellID = 1289192, time = 274, observations = 16 },
                                { spellID = 1288538, time = 291, observations = 11 },
                                { spellID = 1288538, time = 295, observations = 11 },
                                { spellID = 1288538, time = 298, observations = 9 },
                                { spellID = 1291404, time = 305, observations = 8 },
                                { spellID = 1290809, time = 314, observations = 7 },
                                { spellID = 1290956, time = 323, observations = 7 },
                                { spellID = 1290516, time = 335, observations = 7 },
                                { spellID = 1294293, time = 356, observations = 4 },
                                { spellID = 1306872, time = 356, observations = 6 },
                                { spellID = 1289192, time = 385, observations = 4 },
                            },
                        },
                    },
                },
            },
        },
        [3429] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Serpent's Bargain",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1282487, time = 0, observations = 30 },
                                { spellID = 1299960, time = 2, observations = 30 },
                                { spellID = 1283832, time = 12, observations = 30 },
                                { spellID = 1283485, time = 42, observations = 30 },
                                { spellID = 1283489, time = 42, observations = 30 },
                                { spellID = 1299960, time = 44, observations = 30 },
                                { spellID = 1282487, time = 85, observations = 30 },
                                { spellID = 1299960, time = 87, observations = 30 },
                                { spellID = 1283832, time = 97, observations = 30 },
                                { spellID = 1283485, time = 127, observations = 4 },
                                { spellID = 1283489, time = 127, observations = 4 },
                                { spellID = 1299960, time = 129, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Usurper's Reprisal",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286918, time = 78, observations = 30 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Claimed Vessel",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Coiled Union",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298381, time = 3, observations = 30 },
                                { spellID = 1299960, time = 5, observations = 30 },
                                { spellID = 1286918, time = 37, observations = 30 },
                                { spellID = 1299960, time = 46, observations = 30 },
                                { spellID = 1298381, time = 95, observations = 30 },
                                { spellID = 1299960, time = 96, observations = 30 },
                                { spellID = 1286918, time = 124, observations = 30 },
                                { spellID = 1299960, time = 133, observations = 30 },
                                { spellID = 1298381, time = 186, observations = 5 },
                                { spellID = 1299960, time = 187, observations = 8 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Serpent's Bargain",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1282487, time = 0, observations = 30 },
                                { spellID = 1299960, time = 2, observations = 30 },
                                { spellID = 1283832, time = 12, observations = 30 },
                                { spellID = 1283485, time = 43, observations = 30 },
                                { spellID = 1283489, time = 43, observations = 30 },
                                { spellID = 1299960, time = 45, observations = 30 },
                                { spellID = 1282487, time = 85, observations = 30 },
                                { spellID = 1299960, time = 87, observations = 30 },
                                { spellID = 1283832, time = 97, observations = 30 },
                                { spellID = 1283485, time = 128, observations = 26 },
                                { spellID = 1283489, time = 128, observations = 26 },
                                { spellID = 1299960, time = 130, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Usurper's Reprisal",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286441, time = 21, observations = 30 },
                                { spellID = 1286441, time = 54, observations = 30 },
                                { spellID = 1286918, time = 78, observations = 30 },
                                { spellID = 1286441, time = 106, observations = 30 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Claimed Vessel",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Coiled Union",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298381, time = 3, observations = 30 },
                                { spellID = 1299960, time = 5, observations = 30 },
                                { spellID = 1299266, time = 20, observations = 30 },
                                { spellID = 1286918, time = 42, observations = 30 },
                                { spellID = 1299960, time = 52, observations = 30 },
                                { spellID = 1298381, time = 108, observations = 30 },
                                { spellID = 1299960, time = 110, observations = 30 },
                                { spellID = 1286918, time = 142, observations = 30 },
                                { spellID = 1299960, time = 152, observations = 30 },
                                { spellID = 1299266, time = 190, observations = 17 },
                                { spellID = 1298381, time = 213, observations = 6 },
                                { spellID = 1299960, time = 214, observations = 6 },
                            },
                        },
                    },
                },
            },
        },
        [3445] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 10, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 16, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 73, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 10, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 48, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 70, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 29 },
                                { spellID = 1284487, time = 28, observations = 29 },
                                { spellID = 1284483, time = 40, observations = 27 },
                                { spellID = 1284434, time = 46, observations = 24 },
                                { spellID = 1284458, time = 49, observations = 24 },
                                { spellID = 1284487, time = 50, observations = 21 },
                                { spellID = 1288232, time = 58, observations = 8 },
                                { spellID = 1284251, time = 63, observations = 14 },
                                { spellID = 1284458, time = 71, observations = 7 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 73, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 22 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 22 },
                                { spellID = 1284251, time = 63, observations = 22 },
                                { spellID = 1284458, time = 71, observations = 22 },
                                { spellID = 1284487, time = 73, observations = 22 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 40, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 50, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 72, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 73, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 22 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 22 },
                                { spellID = 1284434, time = 13, observations = 22 },
                                { spellID = 1288232, time = 17, observations = 20 },
                                { spellID = 1284458, time = 27, observations = 17 },
                                { spellID = 1284487, time = 29, observations = 18 },
                                { spellID = 1284483, time = 41, observations = 13 },
                                { spellID = 1284434, time = 46, observations = 16 },
                                { spellID = 1284458, time = 49, observations = 13 },
                                { spellID = 1284487, time = 51, observations = 8 },
                                { spellID = 1288232, time = 58, observations = 5 },
                                { spellID = 1284251, time = 63, observations = 6 },
                            },
                        },
                    },
                },
            },
        },
        [3455] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1280935, time = 8, observations = 30 },
                                { spellID = 1280935, time = 26, observations = 30 },
                                { spellID = 1280935, time = 59, observations = 30 },
                                { spellID = 1280935, time = 89, observations = 30 },
                                { spellID = 1280935, time = 110, observations = 30 },
                                { spellID = 1280935, time = 143, observations = 30 },
                                { spellID = 1280935, time = 173, observations = 30 },
                                { spellID = 1280935, time = 194, observations = 30 },
                                { spellID = 1280935, time = 227, observations = 30 },
                                { spellID = 1280935, time = 257, observations = 30 },
                                { spellID = 1280935, time = 278, observations = 21 },
                                { spellID = 1280935, time = 311, observations = 14 },
                                { spellID = 1280935, time = 341, observations = 5 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Phase 1",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1280935, time = 8, observations = 30 },
                                { spellID = 1282509, time = 30, observations = 30 },
                                { spellID = 1280935, time = 37, observations = 30 },
                                { spellID = 1280935, time = 64, observations = 30 },
                                { spellID = 1282509, time = 69, observations = 30 },
                                { spellID = 1280935, time = 92, observations = 30 },
                                { spellID = 1282509, time = 114, observations = 30 },
                                { spellID = 1280935, time = 121, observations = 30 },
                                { spellID = 1280935, time = 148, observations = 30 },
                                { spellID = 1282509, time = 153, observations = 30 },
                                { spellID = 1280935, time = 176, observations = 30 },
                                { spellID = 1282509, time = 198, observations = 30 },
                                { spellID = 1280935, time = 205, observations = 30 },
                                { spellID = 1280935, time = 232, observations = 30 },
                                { spellID = 1282509, time = 237, observations = 30 },
                                { spellID = 1280935, time = 260, observations = 30 },
                                { spellID = 1282509, time = 282, observations = 30 },
                                { spellID = 1280935, time = 289, observations = 30 },
                                { spellID = 1280935, time = 316, observations = 30 },
                                { spellID = 1282509, time = 321, observations = 30 },
                                { spellID = 1280935, time = 344, observations = 30 },
                                { spellID = 1282509, time = 366, observations = 30 },
                                { spellID = 1280935, time = 373, observations = 30 },
                                { spellID = 1280935, time = 400, observations = 23 },
                                { spellID = 1282509, time = 405, observations = 21 },
                                { spellID = 1280935, time = 428, observations = 10 },
                            },
                        },
                    },
                },
            },
        },
        [3470] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 30 },
                                { spellID = 1284103, time = 28, observations = 30 },
                                { spellID = 1287533, time = 53, observations = 30 },
                                { spellID = 1287533, time = 54, observations = 30 },
                                { spellID = 1287533, time = 55, observations = 29 },
                                { spellID = 1284103, time = 64, observations = 30 },
                                { spellID = 1285681, time = 77, observations = 20 },
                                { spellID = 1284103, time = 99, observations = 19 },
                                { spellID = 1287533, time = 121, observations = 13 },
                                { spellID = 1287533, time = 122, observations = 13 },
                                { spellID = 1287533, time = 124, observations = 8 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 36, observations = 25 },
                                { spellID = 1287533, time = 37, observations = 25 },
                                { spellID = 1287533, time = 39, observations = 24 },
                                { spellID = 1287533, time = 87, observations = 12 },
                                { spellID = 1287533, time = 89, observations = 17 },
                                { spellID = 1287533, time = 90, observations = 17 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 30 },
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 38, observations = 30 },
                                { spellID = 1284103, time = 45, observations = 30 },
                                { spellID = 1299673, time = 61, observations = 30 },
                                { spellID = 1284103, time = 73, observations = 30 },
                                { spellID = 1287533, time = 75, observations = 29 },
                                { spellID = 1287533, time = 76, observations = 28 },
                                { spellID = 1287533, time = 78, observations = 21 },
                                { spellID = 1299673, time = 93, observations = 17 },
                                { spellID = 1287533, time = 115, observations = 12 },
                                { spellID = 1287533, time = 116, observations = 10 },
                                { spellID = 1287533, time = 117, observations = 6 },
                                { spellID = 1284103, time = 125, observations = 6 },
                                { spellID = 1299673, time = 141, observations = 3 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 30 },
                                { spellID = 1284103, time = 28, observations = 30 },
                                { spellID = 1287533, time = 53, observations = 30 },
                                { spellID = 1287533, time = 54, observations = 30 },
                                { spellID = 1287533, time = 55, observations = 30 },
                                { spellID = 1284103, time = 64, observations = 30 },
                                { spellID = 1285681, time = 78, observations = 30 },
                                { spellID = 1284103, time = 99, observations = 30 },
                                { spellID = 1287533, time = 121, observations = 30 },
                                { spellID = 1287533, time = 122, observations = 27 },
                                { spellID = 1287533, time = 124, observations = 18 },
                                { spellID = 1284103, time = 135, observations = 28 },
                                { spellID = 1285681, time = 148, observations = 22 },
                                { spellID = 1284103, time = 170, observations = 14 },
                                { spellID = 1287533, time = 192, observations = 5 },
                                { spellID = 1287533, time = 194, observations = 5 },
                                { spellID = 1287533, time = 195, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 37, observations = 30 },
                                { spellID = 1287533, time = 39, observations = 30 },
                                { spellID = 1287533, time = 93, observations = 30 },
                                { spellID = 1287533, time = 97, observations = 29 },
                                { spellID = 1287533, time = 99, observations = 22 },
                                { spellID = 1287533, time = 114, observations = 11 },
                                { spellID = 1287533, time = 121, observations = 6 },
                                { spellID = 1287533, time = 124, observations = 4 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 30 },
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 38, observations = 30 },
                                { spellID = 1284103, time = 45, observations = 30 },
                                { spellID = 1299673, time = 61, observations = 30 },
                                { spellID = 1284103, time = 73, observations = 30 },
                                { spellID = 1287533, time = 75, observations = 30 },
                                { spellID = 1287533, time = 76, observations = 30 },
                                { spellID = 1287533, time = 78, observations = 30 },
                                { spellID = 1299673, time = 93, observations = 30 },
                                { spellID = 1287533, time = 115, observations = 30 },
                                { spellID = 1287533, time = 116, observations = 29 },
                                { spellID = 1287533, time = 118, observations = 24 },
                                { spellID = 1284103, time = 125, observations = 29 },
                                { spellID = 1299673, time = 141, observations = 24 },
                                { spellID = 1284103, time = 153, observations = 20 },
                                { spellID = 1287533, time = 155, observations = 19 },
                                { spellID = 1287533, time = 156, observations = 4 },
                                { spellID = 1287533, time = 157, observations = 17 },
                                { spellID = 1287533, time = 158, observations = 10 },
                                { spellID = 1287533, time = 158, observations = 3 },
                                { spellID = 1299673, time = 173, observations = 10 },
                            },
                        },
                    },
                },
                [16] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 9 },
                                { spellID = 1284103, time = 28, observations = 9 },
                                { spellID = 1287533, time = 53, observations = 9 },
                                { spellID = 1287533, time = 55, observations = 9 },
                                { spellID = 1284103, time = 64, observations = 9 },
                                { spellID = 1285681, time = 78, observations = 9 },
                                { spellID = 1284103, time = 99, observations = 9 },
                                { spellID = 1287533, time = 121, observations = 9 },
                                { spellID = 1287533, time = 122, observations = 9 },
                                { spellID = 1287533, time = 124, observations = 8 },
                                { spellID = 1284103, time = 135, observations = 9 },
                                { spellID = 1285681, time = 149, observations = 9 },
                                { spellID = 1284103, time = 170, observations = 9 },
                                { spellID = 1287533, time = 192, observations = 7 },
                                { spellID = 1287533, time = 193, observations = 5 },
                                { spellID = 1287533, time = 195, observations = 4 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 31, observations = 9 },
                                { spellID = 1287533, time = 32, observations = 9 },
                                { spellID = 1287533, time = 34, observations = 9 },
                                { spellID = 1287533, time = 69, observations = 9 },
                                { spellID = 1287533, time = 98, observations = 9 },
                                { spellID = 1287533, time = 106, observations = 9 },
                                { spellID = 1287533, time = 107, observations = 8 },
                                { spellID = 1287533, time = 125, observations = 8 },
                                { spellID = 1287533, time = 139, observations = 6 },
                                { spellID = 1287533, time = 139, observations = 4 },
                                { spellID = 1287533, time = 142, observations = 4 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 9 },
                                { spellID = 1287533, time = 35, observations = 9 },
                                { spellID = 1287533, time = 36, observations = 9 },
                                { spellID = 1287533, time = 38, observations = 9 },
                                { spellID = 1284103, time = 45, observations = 9 },
                                { spellID = 1299673, time = 61, observations = 9 },
                                { spellID = 1284103, time = 73, observations = 9 },
                                { spellID = 1287533, time = 75, observations = 9 },
                                { spellID = 1287533, time = 77, observations = 9 },
                                { spellID = 1287533, time = 78, observations = 9 },
                                { spellID = 1299673, time = 93, observations = 9 },
                                { spellID = 1287533, time = 115, observations = 9 },
                                { spellID = 1287533, time = 117, observations = 9 },
                                { spellID = 1287533, time = 118, observations = 9 },
                                { spellID = 1284103, time = 125, observations = 9 },
                                { spellID = 1299673, time = 141, observations = 9 },
                                { spellID = 1284103, time = 153, observations = 9 },
                                { spellID = 1287533, time = 155, observations = 8 },
                                { spellID = 1287533, time = 156, observations = 7 },
                                { spellID = 1287533, time = 158, observations = 7 },
                                { spellID = 1287533, time = 158, observations = 3 },
                                { spellID = 1299673, time = 173, observations = 8 },
                            },
                        },
                    },
                },
                [17] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 30 },
                                { spellID = 1284103, time = 28, observations = 30 },
                                { spellID = 1287533, time = 53, observations = 29 },
                                { spellID = 1287533, time = 54, observations = 28 },
                                { spellID = 1287533, time = 55, observations = 20 },
                                { spellID = 1284103, time = 64, observations = 10 },
                                { spellID = 1285681, time = 77, observations = 8 },
                                { spellID = 1284103, time = 99, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 36, observations = 10 },
                                { spellID = 1287533, time = 38, observations = 10 },
                                { spellID = 1287533, time = 39, observations = 8 },
                                { spellID = 1287533, time = 83, observations = 6 },
                                { spellID = 1287533, time = 85, observations = 4 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 30 },
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 38, observations = 26 },
                                { spellID = 1284103, time = 45, observations = 30 },
                                { spellID = 1299673, time = 61, observations = 16 },
                                { spellID = 1284103, time = 73, observations = 8 },
                                { spellID = 1287533, time = 75, observations = 7 },
                                { spellID = 1287533, time = 76, observations = 7 },
                                { spellID = 1287533, time = 76, observations = 6 },
                                { spellID = 1287533, time = 76, observations = 3 },
                                { spellID = 1299673, time = 93, observations = 7 },
                            },
                        },
                    },
                },
            },
        },
        [3492] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Fury of the Serpent Mother",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298367, time = 10, observations = 30 },
                                { spellID = 1296301, time = 35, observations = 30 },
                                { spellID = 1298367, time = 72, observations = 30 },
                                { spellID = 1296301, time = 76, observations = 29 },
                                { spellID = 1286860, time = 130, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Children of the Doomscale",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286860, time = 114, observations = 30 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Shattering",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Ula'tek's Ascension",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1300751, time = 4, observations = 30 },
                                { spellID = 1298367, time = 9, observations = 30 },
                                { spellID = 1295905, time = 24, observations = 30 },
                                { spellID = 1300751, time = 69, observations = 30 },
                                { spellID = 1298367, time = 74, observations = 28 },
                                { spellID = 1295905, time = 84, observations = 18 },
                                { spellID = 1295905, time = 124, observations = 4 },
                                { spellID = 1300751, time = 131, observations = 3 },
                            },
                        },
                    },
                },
            },
        },
        [3497] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 20, observations = 4 },
                                { spellID = 1291933, time = 24, observations = 4 },
                                { spellID = 1295854, time = 30, observations = 4 },
                                { spellID = 1291933, time = 51, observations = 4 },
                                { spellID = 1291933, time = 55, observations = 3 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "First Mate Nama: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 53, observations = 4 },
                                { spellID = 1291933, time = 57, observations = 4 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 53, observations = 3 },
                                { spellID = 1297022, time = 56, observations = 4 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Scrollsage Iku: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 9, observations = 4 },
                                { spellID = 1291933, time = 13, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 36, observations = 4 },
                                { spellID = 1291933, time = 40, observations = 4 },
                                { spellID = 1291933, time = 43, observations = 3 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Trader Gebbo: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1292104, time = 5, observations = 3 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 20, observations = 4 },
                                { spellID = 1291933, time = 24, observations = 4 },
                                { spellID = 1295854, time = 30, observations = 4 },
                                { spellID = 1291933, time = 51, observations = 4 },
                                { spellID = 1291933, time = 55, observations = 4 },
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Trader Gebbo: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1292104, time = 5, observations = 4 },
                                { spellID = 1296249, time = 15, observations = 4 },
                                { spellID = 1291933, time = 29, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 33, observations = 4 },
                                { spellID = 1292104, time = 37, observations = 4 },
                                { spellID = 1296249, time = 47, observations = 4 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "First Mate Nama: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 53, observations = 4 },
                                { spellID = 1291933, time = 57, observations = 4 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1297022, time = 53, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Scrollsage Iku: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 9, observations = 4 },
                                { spellID = 1291933, time = 13, observations = 4 },
                                { spellID = 1295854, time = 32, observations = 4 },
                                { spellID = 1291933, time = 36, observations = 4 },
                                { spellID = 1291933, time = 40, observations = 4 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 4 },
                                { spellID = 1291933, time = 26, observations = 4 },
                            },
                        },
                    },
                },
            },
        },
    },
}
