local PRT = PurplexityRaidTools

PRT.BossTimelineData = {
    schemaVersion = 1,
    encounters = {
        [3420] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 36, observations = 9 },
                                { spellID = 1285425, time = 50, observations = 9 },
                                { spellID = 1305959, time = 95, observations = 9 },
                                { spellID = 1285425, time = 108, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 38, observations = 9 },
                                { spellID = 1285425, time = 52, observations = 9 },
                                { spellID = 1305959, time = 97, observations = 9 },
                                { spellID = 1285425, time = 110, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 32, observations = 19 },
                                { spellID = 1285425, time = 44, observations = 19 },
                                { spellID = 1305959, time = 84, observations = 19 },
                                { spellID = 1285425, time = 96, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 34, observations = 19 },
                                { spellID = 1285425, time = 46, observations = 19 },
                                { spellID = 1305959, time = 86, observations = 19 },
                                { spellID = 1285425, time = 98, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1305959, time = 34, observations = 19 },
                                { spellID = 1285425, time = 46, observations = 19 },
                                { spellID = 1305959, time = 86, observations = 19 },
                                { spellID = 1285425, time = 98, observations = 19 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Howling Maelstrom",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Sszorak",
                            isIntermission = false,
                            occurrences = {
                            },
                        },
                    },
                },
            },
        },
        [3429] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Serpent's Bargain",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1282487, time = 0, observations = 30 },
                                { spellID = 1299960, time = 2, observations = 30 },
                                { spellID = 1283832, time = 12, observations = 30 },
                                { spellID = 1283485, time = 42, observations = 30 },
                                { spellID = 1283489, time = 42, observations = 30 },
                                { spellID = 1299960, time = 44, observations = 30 },
                                { spellID = 1282487, time = 85, observations = 30 },
                                { spellID = 1299960, time = 87, observations = 30 },
                                { spellID = 1283832, time = 97, observations = 30 },
                                { spellID = 1283485, time = 127, observations = 4 },
                                { spellID = 1283489, time = 127, observations = 4 },
                                { spellID = 1299960, time = 129, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Usurper's Reprisal",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286918, time = 78, observations = 30 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Claimed Vessel",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Coiled Union",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298381, time = 3, observations = 30 },
                                { spellID = 1299960, time = 5, observations = 30 },
                                { spellID = 1286918, time = 37, observations = 30 },
                                { spellID = 1299960, time = 46, observations = 30 },
                                { spellID = 1298381, time = 95, observations = 30 },
                                { spellID = 1299960, time = 96, observations = 30 },
                                { spellID = 1286918, time = 124, observations = 30 },
                                { spellID = 1299960, time = 133, observations = 30 },
                                { spellID = 1298381, time = 186, observations = 5 },
                                { spellID = 1299960, time = 187, observations = 8 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Serpent's Bargain",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1282487, time = 0, observations = 4 },
                                { spellID = 1299960, time = 2, observations = 4 },
                                { spellID = 1283832, time = 12, observations = 4 },
                                { spellID = 1283485, time = 43, observations = 4 },
                                { spellID = 1283489, time = 43, observations = 4 },
                                { spellID = 1299960, time = 45, observations = 4 },
                                { spellID = 1282487, time = 85, observations = 4 },
                                { spellID = 1299960, time = 87, observations = 4 },
                                { spellID = 1283832, time = 97, observations = 4 },
                                { spellID = 1283485, time = 128, observations = 4 },
                                { spellID = 1283489, time = 128, observations = 4 },
                                { spellID = 1299960, time = 130, observations = 4 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Usurper's Reprisal",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286441, time = 21, observations = 4 },
                                { spellID = 1286441, time = 54, observations = 4 },
                                { spellID = 1286918, time = 78, observations = 4 },
                                { spellID = 1286441, time = 106, observations = 4 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Claimed Vessel",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Coiled Union",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298381, time = 3, observations = 4 },
                                { spellID = 1299960, time = 5, observations = 4 },
                                { spellID = 1299266, time = 20, observations = 4 },
                                { spellID = 1286918, time = 42, observations = 4 },
                                { spellID = 1299960, time = 52, observations = 4 },
                                { spellID = 1298381, time = 108, observations = 4 },
                                { spellID = 1299960, time = 110, observations = 4 },
                                { spellID = 1286918, time = 142, observations = 4 },
                                { spellID = 1299960, time = 152, observations = 4 },
                            },
                        },
                    },
                },
            },
        },
        [3445] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 10, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 16, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 73, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 10, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 48, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 70, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 30 },
                                { spellID = 1284487, time = 29, observations = 30 },
                                { spellID = 1284483, time = 41, observations = 30 },
                                { spellID = 1284434, time = 46, observations = 30 },
                                { spellID = 1284458, time = 49, observations = 30 },
                                { spellID = 1284487, time = 51, observations = 30 },
                                { spellID = 1288232, time = 58, observations = 30 },
                                { spellID = 1284251, time = 63, observations = 30 },
                                { spellID = 1284458, time = 71, observations = 30 },
                                { spellID = 1284487, time = 72, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 30 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 30 },
                                { spellID = 1284487, time = 7, observations = 30 },
                                { spellID = 1284251, time = 11, observations = 30 },
                                { spellID = 1284434, time = 13, observations = 30 },
                                { spellID = 1288232, time = 17, observations = 30 },
                                { spellID = 1284458, time = 27, observations = 29 },
                                { spellID = 1284487, time = 28, observations = 29 },
                                { spellID = 1284483, time = 40, observations = 27 },
                                { spellID = 1284434, time = 46, observations = 24 },
                                { spellID = 1284458, time = 49, observations = 24 },
                                { spellID = 1284487, time = 50, observations = 21 },
                                { spellID = 1288232, time = 58, observations = 8 },
                                { spellID = 1284251, time = 63, observations = 14 },
                                { spellID = 1284458, time = 71, observations = 7 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 73, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 22 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 22 },
                                { spellID = 1284251, time = 63, observations = 22 },
                                { spellID = 1284458, time = 71, observations = 22 },
                                { spellID = 1284487, time = 73, observations = 22 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 40, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 50, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 72, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 23 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 23 },
                                { spellID = 1284434, time = 13, observations = 23 },
                                { spellID = 1288232, time = 17, observations = 23 },
                                { spellID = 1284458, time = 27, observations = 23 },
                                { spellID = 1284487, time = 29, observations = 23 },
                                { spellID = 1284483, time = 41, observations = 23 },
                                { spellID = 1284434, time = 46, observations = 23 },
                                { spellID = 1284458, time = 49, observations = 23 },
                                { spellID = 1284487, time = 51, observations = 23 },
                                { spellID = 1288232, time = 58, observations = 23 },
                                { spellID = 1284251, time = 63, observations = 23 },
                                { spellID = 1284458, time = 71, observations = 23 },
                                { spellID = 1284487, time = 73, observations = 23 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Vitriolic Stasis",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1284588, time = 0, observations = 23 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "Stage One: Entombed Sentinels",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1284458, time = 5, observations = 22 },
                                { spellID = 1284487, time = 7, observations = 23 },
                                { spellID = 1284251, time = 11, observations = 22 },
                                { spellID = 1284434, time = 13, observations = 22 },
                                { spellID = 1288232, time = 17, observations = 20 },
                                { spellID = 1284458, time = 27, observations = 17 },
                                { spellID = 1284487, time = 29, observations = 18 },
                                { spellID = 1284483, time = 41, observations = 13 },
                                { spellID = 1284434, time = 46, observations = 16 },
                                { spellID = 1284458, time = 49, observations = 13 },
                                { spellID = 1284487, time = 51, observations = 8 },
                                { spellID = 1288232, time = 58, observations = 5 },
                                { spellID = 1284251, time = 63, observations = 6 },
                            },
                        },
                    },
                },
            },
        },
        [3470] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 30 },
                                { spellID = 1284103, time = 28, observations = 30 },
                                { spellID = 1287533, time = 53, observations = 30 },
                                { spellID = 1287533, time = 54, observations = 30 },
                                { spellID = 1287533, time = 55, observations = 30 },
                                { spellID = 1284103, time = 64, observations = 30 },
                                { spellID = 1285681, time = 78, observations = 30 },
                                { spellID = 1284103, time = 99, observations = 30 },
                                { spellID = 1287533, time = 121, observations = 30 },
                                { spellID = 1287533, time = 122, observations = 30 },
                                { spellID = 1287533, time = 124, observations = 27 },
                                { spellID = 1284103, time = 135, observations = 30 },
                                { spellID = 1285681, time = 149, observations = 29 },
                                { spellID = 1284103, time = 170, observations = 25 },
                                { spellID = 1287533, time = 192, observations = 20 },
                                { spellID = 1287533, time = 193, observations = 18 },
                                { spellID = 1287533, time = 195, observations = 14 },
                                { spellID = 1284103, time = 206, observations = 3 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 37, observations = 30 },
                                { spellID = 1287533, time = 39, observations = 30 },
                                { spellID = 1287533, time = 76, observations = 30 },
                                { spellID = 1287533, time = 78, observations = 30 },
                                { spellID = 1287533, time = 79, observations = 28 },
                                { spellID = 1287533, time = 120, observations = 23 },
                                { spellID = 1287533, time = 121, observations = 20 },
                                { spellID = 1287533, time = 126, observations = 16 },
                                { spellID = 1287533, time = 159, observations = 8 },
                                { spellID = 1287533, time = 160, observations = 8 },
                                { spellID = 1287533, time = 162, observations = 5 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 30 },
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 38, observations = 30 },
                                { spellID = 1284103, time = 45, observations = 30 },
                                { spellID = 1299673, time = 61, observations = 30 },
                                { spellID = 1284103, time = 73, observations = 30 },
                                { spellID = 1287533, time = 75, observations = 30 },
                                { spellID = 1287533, time = 76, observations = 30 },
                                { spellID = 1287533, time = 78, observations = 30 },
                                { spellID = 1299673, time = 93, observations = 30 },
                                { spellID = 1287533, time = 115, observations = 30 },
                                { spellID = 1287533, time = 116, observations = 30 },
                                { spellID = 1287533, time = 118, observations = 30 },
                                { spellID = 1284103, time = 125, observations = 30 },
                                { spellID = 1299673, time = 141, observations = 30 },
                                { spellID = 1284103, time = 153, observations = 30 },
                                { spellID = 1287533, time = 155, observations = 30 },
                                { spellID = 1287533, time = 155, observations = 19 },
                                { spellID = 1287533, time = 156, observations = 29 },
                                { spellID = 1287533, time = 156, observations = 16 },
                                { spellID = 1287533, time = 158, observations = 14 },
                                { spellID = 1287533, time = 158, observations = 8 },
                                { spellID = 1299673, time = 173, observations = 24 },
                                { spellID = 1287533, time = 195, observations = 6 },
                                { spellID = 1287533, time = 197, observations = 4 },
                                { spellID = 1284103, time = 205, observations = 3 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Soulcoiler Initiation",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1285681, time = 3, observations = 30 },
                                { spellID = 1284103, time = 28, observations = 30 },
                                { spellID = 1287533, time = 53, observations = 30 },
                                { spellID = 1287533, time = 54, observations = 30 },
                                { spellID = 1287533, time = 55, observations = 30 },
                                { spellID = 1284103, time = 64, observations = 30 },
                                { spellID = 1285681, time = 78, observations = 30 },
                                { spellID = 1284103, time = 99, observations = 30 },
                                { spellID = 1287533, time = 121, observations = 29 },
                                { spellID = 1287533, time = 122, observations = 29 },
                                { spellID = 1287533, time = 124, observations = 22 },
                                { spellID = 1284103, time = 135, observations = 29 },
                                { spellID = 1285681, time = 149, observations = 30 },
                                { spellID = 1284103, time = 170, observations = 23 },
                                { spellID = 1287533, time = 192, observations = 15 },
                                { spellID = 1287533, time = 193, observations = 13 },
                                { spellID = 1287533, time = 195, observations = 9 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Intermission: Ritual of Awakening",
                            isIntermission = true,
                            occurrences = {
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 37, observations = 30 },
                                { spellID = 1287533, time = 39, observations = 30 },
                                { spellID = 1287533, time = 76, observations = 30 },
                                { spellID = 1287533, time = 78, observations = 30 },
                                { spellID = 1287533, time = 79, observations = 25 },
                                { spellID = 1287533, time = 118, observations = 22 },
                                { spellID = 1287533, time = 122, observations = 20 },
                                { spellID = 1287533, time = 125, observations = 14 },
                                { spellID = 1287533, time = 128, observations = 11 },
                                { spellID = 1287533, time = 154, observations = 11 },
                                { spellID = 1287533, time = 162, observations = 5 },
                                { spellID = 1287533, time = 163, observations = 8 },
                                { spellID = 1287533, time = 165, observations = 4 },
                                { spellID = 1287533, time = 167, observations = 3 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Stage Two: Uncoiling",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1299673, time = 13, observations = 30 },
                                { spellID = 1287533, time = 35, observations = 30 },
                                { spellID = 1287533, time = 36, observations = 30 },
                                { spellID = 1287533, time = 38, observations = 30 },
                                { spellID = 1284103, time = 45, observations = 30 },
                                { spellID = 1299673, time = 61, observations = 30 },
                                { spellID = 1284103, time = 73, observations = 30 },
                                { spellID = 1287533, time = 75, observations = 30 },
                                { spellID = 1287533, time = 76, observations = 30 },
                                { spellID = 1287533, time = 78, observations = 30 },
                                { spellID = 1299673, time = 93, observations = 30 },
                                { spellID = 1287533, time = 115, observations = 30 },
                                { spellID = 1287533, time = 116, observations = 30 },
                                { spellID = 1287533, time = 118, observations = 30 },
                                { spellID = 1284103, time = 125, observations = 30 },
                                { spellID = 1299673, time = 141, observations = 30 },
                                { spellID = 1284103, time = 153, observations = 29 },
                                { spellID = 1287533, time = 155, observations = 29 },
                                { spellID = 1287533, time = 156, observations = 25 },
                                { spellID = 1287533, time = 158, observations = 20 },
                                { spellID = 1299673, time = 173, observations = 25 },
                                { spellID = 1287533, time = 195, observations = 13 },
                                { spellID = 1287533, time = 196, observations = 10 },
                                { spellID = 1287533, time = 198, observations = 3 },
                                { spellID = 1284103, time = 205, observations = 3 },
                            },
                        },
                    },
                },
            },
        },
        [3492] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "Stage One: Fury of the Serpent Mother",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1298367, time = 10, observations = 30 },
                                { spellID = 1296301, time = 35, observations = 30 },
                                { spellID = 1298367, time = 72, observations = 30 },
                                { spellID = 1296301, time = 76, observations = 29 },
                                { spellID = 1286860, time = 130, observations = 30 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Stage Two: Children of the Doomscale",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1286860, time = 114, observations = 30 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "Intermission: The Shattering",
                            isIntermission = true,
                            occurrences = {
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Stage Three: Ula'tek's Ascension",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1300751, time = 4, observations = 30 },
                                { spellID = 1298367, time = 9, observations = 30 },
                                { spellID = 1295905, time = 24, observations = 30 },
                                { spellID = 1300751, time = 69, observations = 30 },
                                { spellID = 1298367, time = 74, observations = 28 },
                                { spellID = 1295905, time = 84, observations = 18 },
                                { spellID = 1295905, time = 124, observations = 4 },
                                { spellID = 1300751, time = 131, observations = 3 },
                            },
                        },
                    },
                },
            },
        },
        [3497] = {
            difficulties = {
                [14] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 20, observations = 30 },
                                { spellID = 1291933, time = 24, observations = 30 },
                                { spellID = 1295854, time = 30, observations = 30 },
                                { spellID = 1291933, time = 51, observations = 24 },
                                { spellID = 1291933, time = 55, observations = 19 },
                                { spellID = 1292779, time = 60, observations = 11 },
                                { spellID = 1297022, time = 60, observations = 25 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Scrollsage Iku: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1297022, time = 0, observations = 5 },
                                { spellID = 1291933, time = 9, observations = 30 },
                                { spellID = 1291933, time = 13, observations = 30 },
                                { spellID = 1295854, time = 32, observations = 30 },
                                { spellID = 1291933, time = 36, observations = 30 },
                                { spellID = 1291933, time = 40, observations = 30 },
                                { spellID = 1291933, time = 43, observations = 11 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 30 },
                                { spellID = 1291933, time = 26, observations = 30 },
                                { spellID = 1295854, time = 32, observations = 30 },
                                { spellID = 1291933, time = 53, observations = 26 },
                                { spellID = 1291933, time = 57, observations = 16 },
                                { spellID = 1292779, time = 60, observations = 7 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "First Mate Nama: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 30 },
                                { spellID = 1291933, time = 26, observations = 30 },
                                { spellID = 1295854, time = 32, observations = 30 },
                                { spellID = 1291933, time = 53, observations = 30 },
                                { spellID = 1291933, time = 57, observations = 30 },
                                { spellID = 1291933, time = 57, observations = 6 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 30 },
                                { spellID = 1291933, time = 26, observations = 30 },
                                { spellID = 1295854, time = 32, observations = 29 },
                                { spellID = 1291933, time = 53, observations = 23 },
                                { spellID = 1291933, time = 57, observations = 13 },
                                { spellID = 1291933, time = 60, observations = 6 },
                                { spellID = 1292779, time = 60, observations = 8 },
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Trader Gebbo: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1292104, time = 5, observations = 29 },
                                { spellID = 1296249, time = 15, observations = 29 },
                                { spellID = 1291933, time = 29, observations = 29 },
                                { spellID = 1295854, time = 32, observations = 29 },
                                { spellID = 1291933, time = 33, observations = 29 },
                                { spellID = 1291933, time = 33, observations = 8 },
                                { spellID = 1291933, time = 36, observations = 3 },
                                { spellID = 1292104, time = 37, observations = 29 },
                                { spellID = 1296249, time = 47, observations = 29 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 25 },
                                { spellID = 1291933, time = 26, observations = 24 },
                                { spellID = 1295854, time = 32, observations = 26 },
                                { spellID = 1291933, time = 53, observations = 18 },
                                { spellID = 1291933, time = 57, observations = 14 },
                                { spellID = 1292779, time = 60, observations = 18 },
                                { spellID = 1291933, time = 82, observations = 4 },
                                { spellID = 1291933, time = 86, observations = 3 },
                            },
                        },
                    },
                },
                [15] = {
                    phases = {
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 20, observations = 13 },
                                { spellID = 1291933, time = 24, observations = 13 },
                                { spellID = 1295854, time = 30, observations = 13 },
                                { spellID = 1291933, time = 51, observations = 11 },
                                { spellID = 1291933, time = 55, observations = 10 },
                                { spellID = 1292779, time = 60, observations = 6 },
                            },
                        },
                        {
                            phaseID = 3,
                            name = "First Mate Nama: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 13 },
                                { spellID = 1291933, time = 26, observations = 13 },
                                { spellID = 1295854, time = 32, observations = 13 },
                                { spellID = 1291933, time = 53, observations = 13 },
                                { spellID = 1291933, time = 57, observations = 13 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 13 },
                                { spellID = 1291933, time = 26, observations = 13 },
                                { spellID = 1295854, time = 32, observations = 13 },
                                { spellID = 1291933, time = 53, observations = 9 },
                                { spellID = 1291933, time = 57, observations = 8 },
                                { spellID = 1297022, time = 59, observations = 10 },
                                { spellID = 1291933, time = 60, observations = 3 },
                                { spellID = 1292779, time = 60, observations = 4 },
                            },
                        },
                        {
                            phaseID = 2,
                            name = "Scrollsage Iku: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1297022, time = 0, observations = 3 },
                                { spellID = 1291933, time = 9, observations = 13 },
                                { spellID = 1291933, time = 13, observations = 13 },
                                { spellID = 1295854, time = 32, observations = 13 },
                                { spellID = 1291933, time = 36, observations = 13 },
                                { spellID = 1291933, time = 40, observations = 13 },
                                { spellID = 1291933, time = 40, observations = 3 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 13 },
                                { spellID = 1291933, time = 26, observations = 13 },
                                { spellID = 1295854, time = 32, observations = 13 },
                                { spellID = 1291933, time = 53, observations = 10 },
                                { spellID = 1291933, time = 57, observations = 8 },
                                { spellID = 1292779, time = 62, observations = 3 },
                            },
                        },
                        {
                            phaseID = 4,
                            name = "Trader Gebbo: Binding Anguish",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1292104, time = 5, observations = 13 },
                                { spellID = 1296249, time = 15, observations = 13 },
                                { spellID = 1291933, time = 29, observations = 13 },
                                { spellID = 1295854, time = 32, observations = 13 },
                                { spellID = 1291933, time = 33, observations = 13 },
                                { spellID = 1291933, time = 33, observations = 3 },
                                { spellID = 1292104, time = 37, observations = 13 },
                                { spellID = 1296249, time = 47, observations = 13 },
                            },
                        },
                        {
                            phaseID = 1,
                            name = "The Lost Explorers",
                            isIntermission = false,
                            occurrences = {
                                { spellID = 1291933, time = 22, observations = 12 },
                                { spellID = 1291933, time = 26, observations = 11 },
                                { spellID = 1295854, time = 32, observations = 9 },
                                { spellID = 1291933, time = 53, observations = 5 },
                                { spellID = 1291933, time = 57, observations = 3 },
                                { spellID = 1292779, time = 60, observations = 4 },
                            },
                        },
                    },
                },
            },
        },
    },
}
